# Static HTML for /built_with (fallback when built_with.jqx returns empty).
# Run with: jq -n -r -f built_with.jq
[
  "<!DOCTYPE html>",
  "<html lang=\"en\">",
  "<head>",
  "  <meta charset=\"utf-8\">",
  "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
  "  <title>Built with – jqyml</title>",
  "  <link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\">",
  "  <style>",
  "    * { box-sizing: border-box; }",
  "    body { font-family: system-ui, sans-serif; max-width: 42rem; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; background: #f8f8f8; }",
  "    h1 { font-size: 1.5rem; font-weight: 600; margin-bottom: 0.5rem; }",
  "    h2 { font-size: 1.15rem; margin-top: 1.5rem; margin-bottom: 0.5rem; }",
  "    p { color: #555; margin-bottom: 1rem; line-height: 1.5; }",
  "    .counter-box { padding: 0.5rem 0; font-size: 0.875rem; }",
  "    .counter-box .count { font-weight: 600; }",
  "    pre, code { font-family: ui-monospace, monospace; font-size: 0.8125rem; background: #1a1a1a; color: #e0e0e0; border-radius: 6px; }",
  "    pre { padding: 1rem; overflow: auto; margin: 0.5rem 0 1rem; }",
  "    code { padding: 0.2em 0.4em; }",
  "    pre code { padding: 0; background: none; }",
  "    a { color: #333; text-decoration: underline; }",
  "    a:hover { color: #555; }",
  "    .header-links { display: flex; align-items: center; flex-wrap: wrap; gap: 1rem; }",
  "    .header-links a { font-size: 0.875rem; }",
  "  </style>",
  "</head>",
  "<body>",
  "  <header style=\"display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 1rem; margin-bottom: 1.5rem; padding-bottom: 1rem; border-bottom: 1px solid #ddd;\">",
  "    <div class=\"header-links\">",
  "      <h1 style=\"margin: 0; font-size: 1.25rem;\"><a href=\"/\" style=\"text-decoration: none; color: inherit;\">jqyml</a></h1>",
  "      <a href=\"/built_with\">Built with</a>",
  "    </div>",
  "    <div class=\"counter-box\">Visitor count: <span id=\"count\" class=\"count\">—</span></div>",
  "  </header>",
  "  <h1>Built with</h1>",
  "  <p>This site runs on <strong>jq</strong> for all processing and <strong>jqx</strong> for all rendering. No JavaScript frameworks, no Node, no 400 MB of dependencies—just jq and a little Python to hold it together.</p>",
  "  <h2>Processing: jq</h2>",
  "  <p>Every YAML→JSON conversion, state update, and route decision is driven by jq. The YAML parser itself is written in jq (<code>yaml.jq</code>, <code>run.jq</code>). So is the state validator (<code>state.jq</code>). When you paste YAML and click Convert, the server pipes your input into jq and gets JSON back.</p>",
  "  <p>Example: converting YAML to JSON is literally this pipeline:</p>",
  "  <pre><code>jq -R -s -f run.jq   # stdin = YAML, stdout = JSON</code></pre>",
  "  <p>State validation (e.g. POST /state) is jq reading the request and current state and outputting the new state:</p>",
  "  <pre><code>jq -f state.jq       # stdin = { request, current_state }, stdout = { valid, new_state }</code></pre>",
  "  <h2>Rendering: jqx</h2>",
  "  <p>All HTML pages (including this one) are produced by <strong>jqx</strong>: a small jq-based template engine. Templates use <code>{variable}</code> substitution, <code>&lt;If name&gt;...&lt;/If&gt;</code> conditionals, <code>&lt;For item list&gt;...&lt;/For&gt;</code> loops, and <code>&lt;Header /&gt;</code>-style includes. The engine is one jq script (<code>jqx.jq</code>) that expands the template with the given JSON vars.</p>",
  "  <p>Example: a template fragment and the vars passed in:</p>",
  "  <pre><code># Template (e.g. header.jqx):\nVisitor count: &lt;If count_is_zero&gt;No visitors&lt;/If&gt;&lt;If count_gt_0&gt;{count}&lt;/If&gt;\n\n# Vars: { \"count\": 3, \"count_is_zero\": false, \"count_gt_0\": true }\n# Output: Visitor count: 3</code></pre>",
  "  <p>The main index, error pages (404, 400, 401), and this built_with page are all jqx templates rendered with jq.</p>",
  "  <h2>Source</h2>",
  "  <p>Everything is open source. Check out the repo:</p>",
  "  <p><a href=\"https://github.com/bevelwork/jq\" target=\"_blank\" rel=\"noopener\">github.com/bevelwork/jq</a></p>",
  "  <p><a href=\"/\">← Back to converter</a></p>",
  "  <script>",
  "    fetch(\"/state\", { method: \"POST\", headers: { \"Content-Type\": \"application/json\" }, body: JSON.stringify({ counter: 1 }) })",
  "      .then(function(r) { return r.ok ? r.json() : null; })",
  "      .then(function(s) { var el = document.getElementById(\"count\"); if (el && s && typeof s.counter === \"number\") el.textContent = s.counter === 0 ? \"No visitors\" : s.counter; })",
  "      .catch(function() {});",
  "  </script>",
  "</body>",
  "</html>"
] | join("\n")
