# Same as index but no CSS (for /old).
# Run with: jq -n -r -f index_old.jq
[
  "<!DOCTYPE html>",
  "<html lang=\"en\">",
  "<head>",
  "  <meta charset=\"utf-8\">",
  "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
  "  <title>jqyml – YAML to JSON</title>",
  "</head>",
  "<body>",
  "  <h1>jqyml</h1>",
  "  <p>Paste YAML below and click Convert to get JSON. Supports anchors (&amp;name) and aliases (*name).</p>",
  "  <form id=\"f\">",
  "    <label for=\"yaml\">YAML</label>",
  "    <textarea id=\"yaml\" name=\"yaml\" placeholder=\"e.g.&#10;foo: 1&#10;bar: hello\"></textarea>",
  "    <button type=\"submit\">Convert</button>",
  "  </form>",
  "  <div id=\"result\"></div>",
  "  <script>",
  "    document.getElementById(\"f\").onsubmit = function(e) {",
  "      e.preventDefault();",
  "      var result = document.getElementById(\"result\");",
  "      var yaml = document.getElementById(\"yaml\").value;",
  "      if (!yaml.trim()) { result.innerHTML = '<pre class=\"empty\">Paste some YAML first.</pre>'; return; }",
  "      result.innerHTML = '<pre>Converting…</pre>';",
  "      fetch(\"/\", { method: \"POST\", body: yaml, headers: { \"Content-Type\": \"text/plain\" } })",
  "        .then(function(r) { return r.text().then(function(t) { return { ok: r.ok, status: r.status, body: t }; }); })",
  "        .then(function(x) {",
  "          var pre = document.createElement(\"pre\");",
  "          pre.textContent = x.body;",
  "          if (!x.ok) pre.classList.add(\"error\");",
  "          result.innerHTML = \"\";",
  "          result.appendChild(pre);",
  "        })",
  "        .catch(function(err) { result.innerHTML = '<pre class=\"error\">' + err + '</pre>'; });",
  "    };",
  "  </script>",
  "</body>",
  "</html>"
] | join("\n")
